name: CrystalChest
main: com.crystalcraftmc.crystalchest.main.CrystalChest
version: 0.0.1
authors: [Jwood9198, Jacc734, jflory7]
commands:
   CrystalChest:
      description:
         Gives you crystalchest(s)
      aliases:
         [cc]
      usage:
         /<command> <amount>
   NoobWand:
      description:
         Gives you a wand with which to peak in crystalchests
      usage:
         /<command>